const express = require('express');
const path = require('path');
const fs = require('fs');
const config = require('./config');
const { google } = require('googleapis');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(express.json());
app.use(express.static('public'));

// Store replies and webhook logs
let repliesHistory = [];
let webhookLogs = [];

// Google Connection Status
let googleConnectionStatus = {
    connected: false,
    lastCheck: null,
    error: null,
    accountInfo: null
};

// Reply Counters
let replyStats = {
    totalRepliesGenerated: 0,
    totalAutoReplies: 0,
    totalManualReplies: 0,
    totalPosted: 0,
    byRating: {
        '5': 0,
        '4': 0,
        '3': 0,
        '2': 0,
        '1': 0
    },
    byBranch: {},
    last24Hours: []
};

// Load branches
let branches = [];
try {
    const branchesData = fs.readFileSync('./branches.json', 'utf8');
    branches = JSON.parse(branchesData);
    console.log(`✅ Loaded ${branches.length} branches`);
    
    // Initialize branch counters
    branches.forEach(branch => {
        replyStats.byBranch[branch.id] = {
            name: branch.name,
            total: 0,
            positive: 0,
            negative: 0,
            lastReply: null
        };
    });
} catch (error) {
    console.error('Error loading branches:', error);
    branches = [];
}

// ============= GOOGLE BUSINESS API AUTH =============
let googleAuth = null;
let mybusiness = null;

async function initializeGoogleAPI() {
    try {
        if (!process.env.GOOGLE_CREDENTIALS) {
            googleConnectionStatus = {
                connected: false,
                lastCheck: new Date().toISOString(),
                error: 'GOOGLE_CREDENTIALS not set',
                accountInfo: null
            };
            console.log('⚠️ GOOGLE_CREDENTIALS not set, API features disabled');
            return false;
        }
        
        const credentials = JSON.parse(process.env.GOOGLE_CREDENTIALS);
        
        googleAuth = new google.auth.GoogleAuth({
            credentials: credentials,
            scopes: ['https://www.googleapis.com/auth/business.manage']
        });
        
        mybusiness = google.mybusiness({
            version: 'v4',
            auth: googleAuth
        });
        
        // Test connection by fetching accounts
        try {
            const accounts = await mybusiness.accounts.list();
            googleConnectionStatus = {
                connected: true,
                lastCheck: new Date().toISOString(),
                error: null,
                accountInfo: {
                    accountCount: accounts.data.accounts?.length || 0,
                    accounts: accounts.data.accounts?.map(a => ({ name: a.accountName, type: a.type }))
                }
            };
            console.log('✅ Google Business API connected successfully');
            console.log(`📊 Found ${accounts.data.accounts?.length || 0} Google Business accounts`);
            return true;
        } catch (apiError) {
            googleConnectionStatus = {
                connected: false,
                lastCheck: new Date().toISOString(),
                error: apiError.message,
                accountInfo: null
            };
            console.error('❌ Google API test failed:', apiError.message);
            return false;
        }
        
    } catch (error) {
        googleConnectionStatus = {
            connected: false,
            lastCheck: new Date().toISOString(),
            error: error.message,
            accountInfo: null
        };
        console.error('❌ Failed to initialize Google API:', error.message);
        return false;
    }
}

// ============= UPDATE REPLY STATS =============
function updateReplyStats(replyRecord) {
    replyStats.totalRepliesGenerated++;
    
    if (replyRecord.autoGenerated) {
        replyStats.totalAutoReplies++;
    } else {
        replyStats.totalManualReplies++;
    }
    
    if (replyRecord.posted) {
        replyStats.totalPosted++;
    }
    
    // Update rating stats
    const ratingKey = replyRecord.rating.toString();
    if (replyStats.byRating[ratingKey]) {
        replyStats.byRating[ratingKey]++;
    }
    
    // Update branch stats
    if (replyStats.byBranch[replyRecord.branchId]) {
        replyStats.byBranch[replyRecord.branchId].total++;
        if (replyRecord.rating >= 4) {
            replyStats.byBranch[replyRecord.branchId].positive++;
        } else {
            replyStats.byBranch[replyRecord.branchId].negative++;
        }
        replyStats.byBranch[replyRecord.branchId].lastReply = replyRecord.timestamp;
    }
    
    // Update last 24 hours
    const now = new Date();
    replyStats.last24Hours.unshift({
        timestamp: replyRecord.timestamp,
        branchName: replyRecord.branchName,
        rating: replyRecord.rating,
        autoGenerated: replyRecord.autoGenerated,
        posted: replyRecord.posted
    });
    
    // Keep only last 24 hours
    const oneDayAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000);
    replyStats.last24Hours = replyStats.last24Hours.filter(r => new Date(r.timestamp) > oneDayAgo);
}

// ============= GOOGLE REVIEW WEBHOOK =============
app.post('/api/webhook/google-review', async (req, res) => {
    try {
        const reviewData = req.body;
        console.log('📨 Received Google Review Webhook:', reviewData);
        
        webhookLogs.unshift({
            id: Date.now(),
            timestamp: new Date().toISOString(),
            data: reviewData,
            processed: false
        });
        
        const result = await processReviewAutomatically(reviewData);
        
        webhookLogs[0].processed = true;
        webhookLogs[0].result = result;
        
        if (webhookLogs.length > 100) webhookLogs = webhookLogs.slice(0, 100);
        
        res.json({ success: true, message: 'Review received and processed', result });
    } catch (error) {
        console.error('Error processing webhook:', error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// ============= PROCESS REVIEW AUTOMATICALLY =============
async function processReviewAutomatically(reviewData) {
    try {
        const { reviewId, reviewerName, starRating, comment, locationName, locationId } = reviewData;
        
        let branchId = findBranchId(locationName);
        if (!branchId) branchId = findBranchIdByLocationId(locationId);
        if (!branchId) branchId = 1;
        
        const branch = branches.find(b => b.id === branchId);
        const rating = starRating || 5;
        const isPositive = rating >= 4;
        
        let reply;
        if (isPositive) {
            reply = config.getPositiveReply(branchId);
        } else {
            reply = config.getNegativeReply(branchId);
        }
        
        if (reviewerName && reviewerName !== 'Anonymous') {
            reply = `Dear ${reviewerName}, ${reply}`;
        }
        
        let posted = false;
        let postError = null;
        
        // Try to post automatically if Google API is initialized
        if (mybusiness && reviewId && !reviewId.startsWith('test_')) {
            try {
                await postReplyToGoogle(reviewId, reply);
                posted = true;
                console.log(`✅ Auto-reply posted for review ${reviewId}`);
            } catch (error) {
                console.error(`Failed to post reply: ${error.message}`);
                postError = error.message;
            }
        } else if (reviewId && !reviewId.startsWith('test_')) {
            console.log('📝 Auto-reply generated (Google API not connected):', reply);
        }
        
        const replyRecord = {
            id: Date.now(),
            reviewId: reviewId,
            branchId: branchId,
            branchName: branch ? branch.name : locationName,
            rating: rating,
            reviewText: comment,
            reply: reply,
            timestamp: new Date().toISOString(),
            replyType: isPositive ? 'positive' : 'negative',
            autoGenerated: true,
            posted: posted,
            postError: postError
        };
        
        repliesHistory.unshift(replyRecord);
        if (repliesHistory.length > 1000) repliesHistory = repliesHistory.slice(0, 1000);
        
        // Update stats
        updateReplyStats(replyRecord);
        
        return {
            branchId, branchName: branch ? branch.name : locationName,
            rating, reply, autoGenerated: true, posted: posted, postError: postError
        };
        
    } catch (error) {
        console.error('Error in auto-processing:', error);
        throw error;
    }
}

// ============= HELPER FUNCTIONS =============
function findBranchId(locationName) {
    if (!locationName) return null;
    const branchMapping = {
        'Mavdi': 1, 'Rajkot': 1, 'Nadiad': 2, 'Anand': 3, 'Changodar': 4,
        'Bareja': 5, 'Morbi': 6, 'Usmanpura': 7, 'Satellite': 8, 'Juhapura': 9,
        'JUHAPURA': 9, 'Vadaj': 10, 'Sabarmati': 11, 'Naroda': 12,
        'Maninagar': 13, 'Gandhinagar': 14, 'Bapunagar': 15
    };
    for (const [key, id] of Object.entries(branchMapping)) {
        if (locationName.toLowerCase().includes(key.toLowerCase())) return id;
    }
    return null;
}

function findBranchIdByLocationId(locationId) {
    const locationMapping = {};
    return locationMapping[locationId] || null;
}

async function postReplyToGoogle(reviewId, replyText) {
    if (!mybusiness) throw new Error('Google API not initialized');
    
    try {
        const response = await mybusiness.accounts.locations.reviews.reply({
            name: reviewId,
            resource: { comment: replyText }
        });
        return response.data;
    } catch (error) {
        console.error('Google API Error:', error.message);
        throw error;
    }
}

// ============= API: GET GOOGLE CONNECTION STATUS =============
app.get('/api/google-status', (req, res) => {
    res.json({
        success: true,
        status: googleConnectionStatus,
        apiConfigured: !!process.env.GOOGLE_CREDENTIALS
    });
});

// ============= API: GET REPLY STATISTICS =============
app.get('/api/reply-stats', (req, res) => {
    res.json({
        success: true,
        stats: replyStats,
        recentActivity: replyStats.last24Hours.slice(0, 20)
    });
});

// ============= API: Generate Reply (Manual) =============
app.post('/api/get-reply', (req, res) => {
    try {
        const { branchId, reviewText, rating } = req.body;
        
        if (!branchId || !rating) {
            return res.status(400).json({ error: 'Missing required fields: branchId and rating are required' });
        }
        
        const branch = branches.find(b => b.id === parseInt(branchId));
        if (!branch) {
            return res.status(404).json({ error: 'Branch not found' });
        }
        
        const isPositive = rating >= 4;
        let reply;
        
        if (isPositive) {
            reply = config.getPositiveReply(branchId);
        } else {
            reply = config.getNegativeReply(branchId);
        }
        
        const replyRecord = {
            id: Date.now(),
            branchId: branch.id,
            branchName: branch.name,
            rating: rating,
            reviewText: reviewText || '',
            reply: reply,
            timestamp: new Date().toISOString(),
            replyType: isPositive ? 'positive' : 'negative',
            autoGenerated: false,
            posted: false
        };
        
        repliesHistory.unshift(replyRecord);
        if (repliesHistory.length > 1000) repliesHistory = repliesHistory.slice(0, 1000);
        
        // Update stats
        updateReplyStats(replyRecord);
        
        res.json({
            success: true,
            reply: reply,
            branch: branch.name,
            rating: rating,
            templateUsed: isPositive ? 'positive' : 'negative',
            stats: {
                totalReplies: replyStats.totalRepliesGenerated,
                autoReplies: replyStats.totalAutoReplies
            }
        });
        
    } catch (error) {
        console.error('Error generating reply:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

// ============= OTHER API ENDPOINTS =============
app.get('/api/replies', (req, res) => {
    const limit = parseInt(req.query.limit) || 50;
    res.json({ success: true, replies: repliesHistory.slice(0, limit), total: repliesHistory.length });
});

app.get('/api/webhook-logs', (req, res) => {
    res.json({ success: true, logs: webhookLogs.slice(0, 50), total: webhookLogs.length });
});

app.get('/api/branches', (req, res) => {
    res.json({ success: true, branches: branches });
});

app.get('/api/templates', (req, res) => {
    res.json({
        success: true,
        positiveTemplates: config.positiveReplies,
        negativeTemplates: config.negativeReplies,
        counters: config.getCounters()
    });
});

app.post('/api/test-webhook', async (req, res) => {
    const testReview = {
        reviewId: `test_${Date.now()}`,
        reviewerName: "Test Customer",
        starRating: req.body.rating || 5,
        comment: req.body.comment || "Test review comment",
        locationName: req.body.locationName || "Usmanpura Imaging Centre Mavdi, Rajkot",
        locationId: "test_location_123",
        createTime: new Date().toISOString()
    };
    
    const result = await processReviewAutomatically(testReview);
    res.json({ success: true, message: "Test webhook triggered", review: testReview, result });
});

app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

app.get('/health', (req, res) => {
    res.json({
        status: 'healthy',
        branches: branches.length,
        repliesGenerated: replyStats.totalRepliesGenerated,
        autoReplies: replyStats.totalAutoReplies,
        postedReplies: replyStats.totalPosted,
        googleAPIReady: !!mybusiness,
        googleConnected: googleConnectionStatus.connected,
        timestamp: new Date().toISOString()
    });
});

// ============= START SERVER =============
async function startServer() {
    await initializeGoogleAPI();
    
    app.listen(PORT, () => {
        console.log(`🚀 Server running on port ${PORT}`);
        console.log(`📊 Dashboard: https://usmanpura-imaging-review-bot.onrender.com`);
        console.log(`🏥 Branches loaded: ${branches.length}`);
        console.log(`🤖 Google API: ${mybusiness ? '✅ Connected' : '⚠️ Not connected'}`);
        console.log(`📈 Google Connection Status: ${googleConnectionStatus.connected ? 'CONNECTED' : 'DISCONNECTED'}`);
    });
}

startServer();
