const express = require('express');
const path = require('path');
const fs = require('fs');
const config = require('./config');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(express.json());
app.use(express.static('public'));

// Store replies and webhook logs
let repliesHistory = [];
let webhookLogs = [];

// Load branches
let branches = [];
try {
    const branchesData = fs.readFileSync('./branches.json', 'utf8');
    branches = JSON.parse(branchesData);
    console.log(`✅ Loaded ${branches.length} branches`);
} catch (error) {
    console.error('Error loading branches:', error);
    branches = [];
}

// ============= GOOGLE REVIEW WEBHOOK =============
// Endpoint to receive Google review notifications
app.post('/api/webhook/google-review', async (req, res) => {
    try {
        const reviewData = req.body;
        
        console.log('📨 Received Google Review Webhook:', reviewData);
        
        // Log the incoming webhook
        webhookLogs.unshift({
            id: Date.now(),
            timestamp: new Date().toISOString(),
            data: reviewData,
            processed: false
        });
        
        // Process the review
        const result = await processReviewAutomatically(reviewData);
        
        // Update log
        webhookLogs[0].processed = true;
        webhookLogs[0].result = result;
        
        // Keep only last 100 logs
        if (webhookLogs.length > 100) {
            webhookLogs = webhookLogs.slice(0, 100);
        }
        
        res.json({
            success: true,
            message: 'Review received and processed',
            result: result
        });
        
    } catch (error) {
        console.error('Error processing webhook:', error);
        res.status(500).json({
            success: false,
            error: error.message
        });
    }
});

// Function to automatically process review
async function processReviewAutomatically(reviewData) {
    try {
        // Extract review details
        const {
            reviewId,
            reviewerName,
            starRating,
            comment,
            locationName,
            locationId,
            createTime
        } = reviewData;
        
        // Find branch ID from location name
        let branchId = findBranchId(locationName);
        
        // If branch not found, try to match by location ID
        if (!branchId) {
            branchId = findBranchIdByLocationId(locationId);
        }
        
        // Default to branch 1 if not found
        if (!branchId) {
            console.log(`⚠️ Branch not found for ${locationName}, using default`);
            branchId = 1;
        }
        
        // Get the branch name
        const branch = branches.find(b => b.id === branchId);
        
        // Generate reply based on rating
        const rating = starRating || 5;
        const isPositive = rating >= 4;
        
        let reply;
        if (isPositive) {
            reply = config.getPositiveReply(branchId);
        } else {
            reply = config.getNegativeReply(branchId);
        }
        
        // Optional: Personalize reply with reviewer name
        if (reviewerName && reviewerName !== 'Anonymous') {
            reply = `Dear ${reviewerName}, ${reply}`;
        }
        
        // Store in history
        const replyRecord = {
            id: Date.now(),
            reviewId: reviewId,
            branchId: branchId,
            branchName: branch ? branch.name : locationName,
            rating: rating,
            reviewText: comment,
            reply: reply,
            timestamp: new Date().toISOString(),
            replyType: isPositive ? 'positive' : 'negative',
            autoGenerated: true,
            posted: false
        };
        
        repliesHistory.unshift(replyRecord);
        
        // Keep only last 1000 records
        if (repliesHistory.length > 1000) {
            repliesHistory = repliesHistory.slice(0, 1000);
        }
        
        // If you have Google API configured, post automatically
        if (process.env.GOOGLE_API_KEY) {
            try {
                await postReplyToGoogle(reviewId, reply);
                replyRecord.posted = true;
                console.log(`✅ Auto-reply posted for review ${reviewId}`);
            } catch (error) {
                console.error(`Failed to post reply: ${error.message}`);
                replyRecord.postError = error.message;
            }
        } else {
            console.log('📝 Auto-reply generated (manual posting required):', reply);
        }
        
        return {
            branchId: branchId,
            branchName: branch ? branch.name : locationName,
            rating: rating,
            reply: reply,
            autoGenerated: true,
            posted: replyRecord.posted || false
        };
        
    } catch (error) {
        console.error('Error in auto-processing:', error);
        throw error;
    }
}

// Helper function to find branch ID by location name
function findBranchId(locationName) {
    if (!locationName) return null;
    
    const branchMapping = {
        'Mavdi': 1,
        'Rajkot': 1,
        'Nadiad': 2,
        'Anand': 3,
        'Changodar': 4,
        'Bareja': 5,
        'Morbi': 6,
        'Usmanpura': 7,
        'Satellite': 8,
        'Juhapura': 9,
        'JUHAPURA': 9,
        'Vadaj': 10,
        'Sabarmati': 11,
        'Naroda': 12,
        'Maninagar': 13,
        'Gandhinagar': 14,
        'Bapunagar': 15
    };
    
    for (const [key, id] of Object.entries(branchMapping)) {
        if (locationName.toLowerCase().includes(key.toLowerCase())) {
            return id;
        }
    }
    
    return null;
}

function findBranchIdByLocationId(locationId) {
    // You can maintain a mapping of Google Location IDs to your branch IDs
    const locationMapping = {
        // Add your Google location IDs here
        // 'google_location_id_1': 1,
        // 'google_location_id_2': 2,
    };
    
    return locationMapping[locationId] || null;
}

// Function to post reply to Google (if you have API access)
async function postReplyToGoogle(reviewId, replyText) {
    // This is where you'd call Google My Business API
    // For now, it's a placeholder
    console.log(`Would post to review ${reviewId}: ${replyText}`);
    
    // Example using Google API:
    /*
    const { google } = require('googleapis');
    const auth = new google.auth.OAuth2(
        process.env.CLIENT_ID,
        process.env.CLIENT_SECRET,
        process.env.REDIRECT_URI
    );
    
    auth.setCredentials({
        refresh_token: process.env.REFRESH_TOKEN
    });
    
    const mybusiness = google.mybusiness({
        version: 'v4',
        auth: auth
    });
    
    await mybusiness.accounts.locations.reviews.reply({
        name: reviewId,
        resource: {
            comment: replyText
        }
    });
    */
    
    return true;
}

// ============= EXISTING API ENDPOINTS =============

// API: Generate Reply (Manual)
app.post('/api/get-reply', (req, res) => {
    try {
        const { branchId, reviewText, rating } = req.body;
        
        if (!branchId || !rating) {
            return res.status(400).json({ 
                error: 'Missing required fields: branchId and rating are required' 
            });
        }
        
        const branch = branches.find(b => b.id === parseInt(branchId));
        if (!branch) {
            return res.status(404).json({ error: 'Branch not found' });
        }
        
        const isPositive = rating >= 4;
        let reply;
        
        if (isPositive) {
            reply = config.getPositiveReply(branchId);
        } else {
            reply = config.getNegativeReply(branchId);
        }
        
        const replyRecord = {
            id: Date.now(),
            branchId: branch.id,
            branchName: branch.name,
            rating: rating,
            reviewText: reviewText || '',
            reply: reply,
            timestamp: new Date().toISOString(),
            replyType: isPositive ? 'positive' : 'negative',
            autoGenerated: false,
            posted: false
        };
        
        repliesHistory.unshift(replyRecord);
        
        if (repliesHistory.length > 1000) {
            repliesHistory = repliesHistory.slice(0, 1000);
        }
        
        res.json({
            success: true,
            reply: reply,
            branch: branch.name,
            rating: rating,
            templateUsed: isPositive ? 'positive' : 'negative'
        });
        
    } catch (error) {
        console.error('Error generating reply:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

// API: Get Reply History
app.get('/api/replies', (req, res) => {
    const limit = parseInt(req.query.limit) || 50;
    res.json({
        success: true,
        replies: repliesHistory.slice(0, limit),
        total: repliesHistory.length
    });
});

// API: Get Webhook Logs
app.get('/api/webhook-logs', (req, res) => {
    res.json({
        success: true,
        logs: webhookLogs.slice(0, 50),
        total: webhookLogs.length
    });
});

// API: Get All Branches
app.get('/api/branches', (req, res) => {
    res.json({
        success: true,
        branches: branches
    });
});

// API: Get Templates
app.get('/api/templates', (req, res) => {
    res.json({
        success: true,
        positiveTemplates: config.positiveReplies,
        negativeTemplates: config.negativeReplies,
        counters: config.getCounters()
    });
});

// API: Test Webhook (for testing)
app.post('/api/test-webhook', (req, res) => {
    const testReview = {
        reviewId: `test_${Date.now()}`,
        reviewerName: "Test Customer",
        starRating: req.body.rating || 5,
        comment: req.body.comment || "Test review comment",
        locationName: req.body.locationName || "Usmanpura Imaging Centre Mavdi, Rajkot",
        locationId: "test_location_123",
        createTime: new Date().toISOString()
    };
    
    processReviewAutomatically(testReview);
    
    res.json({
        success: true,
        message: "Test webhook triggered",
        review: testReview
    });
});

// Serve Dashboard
app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// Health check
app.get('/health', (req, res) => {
    res.json({ 
        status: 'healthy', 
        branches: branches.length,
        repliesGenerated: repliesHistory.length,
        webhookReceived: webhookLogs.length,
        timestamp: new Date().toISOString()
    });
});

// Start server
app.listen(PORT, () => {
    console.log(`🚀 Server running on port ${PORT}`);
    console.log(`📊 Dashboard: http://localhost:${PORT}`);
    console.log(`🏥 Branches loaded: ${branches.length}`);
    console.log(`💬 Positive templates: ${config.positiveReplies.length}`);
    console.log(`💬 Negative templates: ${config.negativeReplies.length}`);
    console.log(`🤖 Auto-reply webhook: POST /api/webhook/google-review`);
});
